export const craftingEngineAbi = [
  { "inputs": [], "stateMutability": "nonpayable", "type": "constructor" },
  { "inputs": [], "name": "AccessControlBadConfirmation", "type": "error" },
  { "inputs": [{ "internalType": "address", "name": "account", "type": "address" }, { "internalType": "bytes32", "name": "neededRole", "type": "bytes32" }], "name": "AccessControlUnauthorizedAccount", "type": "error" },
  { "inputs": [{ "internalType": "address", "name": "target", "type": "address" }], "name": "AddressEmptyCode", "type": "error" },
  { "inputs": [{ "internalType": "address", "name": "implementation", "type": "address" }], "name": "ERC1967InvalidImplementation", "type": "error" },
  { "inputs": [], "name": "ERC1967NonPayable", "type": "error" },
  { "inputs": [], "name": "FailedCall", "type": "error" },
  { "inputs": [{ "internalType": "uint16", "name": "provided", "type": "uint16" }], "name": "InputAmountTooLow", "type": "error" },
  { "inputs": [{ "internalType": "uint256", "name": "cardId", "type": "uint256" }, { "internalType": "uint256", "name": "required", "type": "uint256" }, { "internalType": "uint256", "name": "held", "type": "uint256" }], "name": "InsufficientCards", "type": "error" },
  { "inputs": [], "name": "InvalidInitialization", "type": "error" },
  { "inputs": [], "name": "InvalidInputCardId", "type": "error" },
  { "inputs": [], "name": "InvalidOutputCardId", "type": "error" },
  { "inputs": [], "name": "NotCrafter", "type": "error" },
  { "inputs": [], "name": "NotInitializing", "type": "error" },
  { "inputs": [{ "internalType": "uint256", "name": "inputCardId", "type": "uint256" }], "name": "RecipeNotFound", "type": "error" },
  { "inputs": [], "name": "ReentrantCall", "type": "error" },
  { "inputs": [{ "internalType": "uint256", "name": "cardId", "type": "uint256" }], "name": "SupplyCapReached", "type": "error" },
  { "inputs": [], "name": "UUPSUnauthorizedCallContext", "type": "error" },
  { "inputs": [{ "internalType": "bytes32", "name": "slot", "type": "bytes32" }], "name": "UUPSUnsupportedProxiableUUID", "type": "error" },
  { "inputs": [], "name": "ZeroTreasuryAddress", "type": "error" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "player", "type": "address" }, { "indexed": true, "internalType": "uint256", "name": "inputCardId", "type": "uint256" }, { "indexed": true, "internalType": "uint256", "name": "outputCardId", "type": "uint256" }], "name": "FusionCrafted", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint64", "name": "version", "type": "uint64" }], "name": "Initialized", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "inputCardId", "type": "uint256" }, { "indexed": true, "internalType": "uint256", "name": "outputCardId", "type": "uint256" }], "name": "RecipeRegistered", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "indexed": true, "internalType": "bytes32", "name": "previousAdminRole", "type": "bytes32" }, { "indexed": true, "internalType": "bytes32", "name": "newAdminRole", "type": "bytes32" }], "name": "RoleAdminChanged", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "indexed": true, "internalType": "address", "name": "account", "type": "address" }, { "indexed": true, "internalType": "address", "name": "sender", "type": "address" }], "name": "RoleGranted", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "indexed": true, "internalType": "address", "name": "account", "type": "address" }, { "indexed": true, "internalType": "address", "name": "sender", "type": "address" }], "name": "RoleRevoked", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "implementation", "type": "address" }], "name": "Upgraded", "type": "event" },
  { "inputs": [], "name": "DEFAULT_ADMIN_ROLE", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "UPGRADER_ROLE", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "UPGRADE_INTERFACE_VERSION", "outputs": [{ "internalType": "string", "name": "", "type": "string" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "cardNFT", "outputs": [{ "internalType": "contract ICardNFT", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "cardRegistry", "outputs": [{ "internalType": "contract ICardRegistry", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "inputCardId", "type": "uint256" }], "name": "fusionCraft", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "inputCardId", "type": "uint256" }], "name": "getRecipe", "outputs": [{ "components": [{ "internalType": "uint256", "name": "inputCardId", "type": "uint256" }, { "internalType": "uint256", "name": "outputCardId", "type": "uint256" }, { "internalType": "uint16", "name": "inputAmount", "type": "uint16" }, { "internalType": "uint120", "name": "shardFee", "type": "uint120" }, { "internalType": "uint120", "name": "veilFee", "type": "uint120" }], "internalType": "struct ICraftingEngine.FusionRecipe", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }], "name": "getRoleAdmin", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "internalType": "address", "name": "account", "type": "address" }], "name": "grantRole", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "inputCardId", "type": "uint256" }], "name": "hasRecipe", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "internalType": "address", "name": "account", "type": "address" }], "name": "hasRole", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "admin", "type": "address" }, { "internalType": "address", "name": "registry_", "type": "address" }, { "internalType": "address", "name": "nft_", "type": "address" }, { "internalType": "address", "name": "shard_", "type": "address" }, { "internalType": "address", "name": "veil_", "type": "address" }, { "internalType": "address", "name": "treasury_", "type": "address" }], "name": "initialize", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "proxiableUUID", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "components": [{ "internalType": "uint256", "name": "inputCardId", "type": "uint256" }, { "internalType": "uint256", "name": "outputCardId", "type": "uint256" }, { "internalType": "uint16", "name": "inputAmount", "type": "uint16" }, { "internalType": "uint120", "name": "shardFee", "type": "uint120" }, { "internalType": "uint120", "name": "veilFee", "type": "uint120" }], "internalType": "struct ICraftingEngine.FusionRecipe", "name": "recipe", "type": "tuple" }], "name": "registerRecipe", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "internalType": "address", "name": "callerConfirmation", "type": "address" }], "name": "renounceRole", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "internalType": "address", "name": "account", "type": "address" }], "name": "revokeRole", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "treasury_", "type": "address" }], "name": "setTreasury", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "shardToken", "outputs": [{ "internalType": "contract IShardToken", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "bytes4", "name": "interfaceId", "type": "bytes4" }], "name": "supportsInterface", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "treasury", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "newImplementation", "type": "address" }, { "internalType": "bytes", "name": "data", "type": "bytes" }], "name": "upgradeToAndCall", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [], "name": "veilToken", "outputs": [{ "internalType": "contract IVeilToken", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }
] as const;
